name: bangalore_metro_app
description: A Flutter web app for Bangalore Metro journey planning
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  http: ^1.1.0
  provider: ^6.1.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true